# Generated by Django 2.0.7 on 2018-08-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='歌曲名称')),
                ('author', models.TextField(verbose_name='创作者')),
                ('pic', models.URLField(blank=True, null=True, verbose_name='封面链接')),
                ('url', models.URLField(verbose_name='歌曲链接')),
            ],
        ),
    ]
