# Generated by Django 2.1 on 2018-09-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180821_1543'),
        ('music', '0002_auto_20180821_0242'),
    ]

    operations = [
    ]
