# Generated by Django 2.1 on 2018-09-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('says', '0004_merge_20180904_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplesays',
            name='name',
            field=models.CharField(default='No name', max_length=12, verbose_name='用户名'),
        ),
    ]
