# Generated by Django 2.0.7 on 2018-08-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=20, verbose_name='Title')),
                ('pin', models.IntegerField(default=1, verbose_name='Pin')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='CreateDate')),
                ('change_date', models.DateField(auto_now=True, verbose_name='ChangeDate')),
                ('main_text', models.TextField(verbose_name='MainText')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=20, verbose_name='Title')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='CreateDate')),
                ('change_date', models.DateField(auto_now=True, verbose_name='ChangeDate')),
                ('main_text', models.TextField(verbose_name='MainText')),
            ],
        ),
    ]
