# Generated by Django 2.1 on 2018-09-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinpost',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='Title'),
        ),
    ]
